global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'webapp'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webapp-service:5000']

  - job_name: 'database'
    static_configs:
      - targets: ['db-service:5432']
